blank_issues_enabled: true
contact_links:
  - name: Feature-Wunsch einreichen
    url: https://github.com/Feberdin/ecoflow-powerocean-ha/issues/new?template=feature_request.md&title=%5BFEATURE%5D%20
    about: Nutze diese Vorlage für neue Funktionen und Verbesserungen.
  - name: Bug melden
    url: https://github.com/Feberdin/ecoflow-powerocean-ha/issues/new?template=bug_report.md&title=%5BBUG%5D%20
    about: Nutze diese Vorlage für Fehlerberichte mit Logs und Reproduktionsschritten.
